# Generated by Django 6.0.6 on 2026-09-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantmenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
