# Generated by Django 6.0.6 on 2026-09-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurant_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='registered_by',
            field=models.ForeignKey(blank=True, help_text='Admin/Employee who registered this restaurant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_restaurants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='subscription_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('starter', 'Starter'), ('premium', 'Premium')], default='basic', max_length=20),
        ),
    ]
