# Generated by Django 6.0.6 on 2026-10-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='menu_file',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/menus/full/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
