# Generated by Django 6.0.6 on 2026-06-13 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_role', models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant')], default='user', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('food_type', models.CharField(choices=[('mexican', 'Mexican'), ('italian', 'Italian'), ('japanese', 'Japanese'), ('chinese', 'Chinese'), ('fast_food', 'Fast Food'), ('bbq', 'BBQ'), ('cafe', 'Cafe'), ('desi', 'Desi'), ('steak', 'Steak'), ('thai', 'Thai'), ('pizza', 'Pizza'), ('bar', 'Bar'), ('grill', 'Grill'), ('american', 'American'), ('other', 'Other')], default='other', max_length=50)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('everyday', 'Everyday'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends')], default='everyday', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('has_time_slots', models.BooleanField(default=False)),
                ('location_branch', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('discount_percentage', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='deals/')),
                ('views_count', models.IntegerField(default=0)),
                ('redemptions_count', models.IntegerField(default=0)),
                ('is_hot_deal', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='restaurants.restaurant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'deal')},
            },
        ),
    ]
