# Generated by Django 6.0.6 on 2026-06-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='created_by_role',
            field=models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
