# Generated by Django 6.0.6 on 2026-10-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_dealview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='food_type',
            field=models.CharField(blank=True, default='other', max_length=500),
        ),
    ]
