# Generated by Django 6.0.6 on 2026-10-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_food_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_duplicates', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='deal',
            name='duplicate_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='deal',
            name='duplicate_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deal',
            name='is_potential_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
