# Generated by Django 6.0.6 on 2026-10-06 10:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, default='', max_length=255)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('rating', models.IntegerField(default=5, help_text='Overall rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ease_of_use', models.IntegerField(default=5, help_text='How easy was the website/app to use? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('usefulness', models.IntegerField(default=5, help_text='How useful is INDULJ? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('smoothness', models.IntegerField(default=5, help_text='How smooth was the experience? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('difficulties', models.TextField(blank=True, default='', help_text='Did they face any difficulties?')),
                ('confusing_aspects', models.TextField(blank=True, default='', help_text='Was anything confusing?')),
                ('feature_requests', models.TextField(blank=True, default='', help_text='What features would they like to see?')),
                ('comments', models.TextField(blank=True, default='', help_text='General suggestions or comments')),
                ('category', models.CharField(choices=[('general', 'General Feedback'), ('usability', 'Ease of Use & Navigation'), ('features', 'Feature Requests'), ('difficulties', 'Issues & Confusing Aspects'), ('deals_happy_hours', 'Deals & Happy Hours')], default='general', max_length=50)),
                ('is_liked', models.BooleanField(default=False, help_text='Super Admin can like/favorite feedback')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('admin_reply', models.TextField(blank=True, default='', help_text='Super Admin response to feedback')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('replied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_feedback_replies', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='feedback_pl_status_822b3f_idx'), models.Index(fields=['is_liked'], name='feedback_pl_is_like_51e4b4_idx'), models.Index(fields=['rating'], name='feedback_pl_rating_a40231_idx'), models.Index(fields=['created_at'], name='feedback_pl_created_263f93_idx')],
            },
        ),
    ]
