# Generated by Django 6.0.6 on 2026-10-06 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Customer & Account Support'), ('restaurant', 'Restaurant Partnership & Listing'), ('deals', 'Deals & Happy Hours'), ('bug', 'Report an Issue / Bug'), ('feedback', 'Feedback & Suggestion'), ('other', 'Other')], default='general', max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who submitted this message, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='contact_con_created_fddb83_idx'), models.Index(fields=['is_read'], name='contact_con_is_read_9a011e_idx'), models.Index(fields=['inquiry_type'], name='contact_con_inquiry_9ff3d4_idx')],
            },
        ),
    ]
