# Generated by Django 6.0.6 on 2026-07-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_referred_by_code_pointstransaction_receiptscan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-last_active']},
        ),
        migrations.AddField(
            model_name='usersession',
            name='browser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='os',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='device_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
