# Generated by Django 6.0.6 on 2026-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usersession_options_usersession_browser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('employee', 'Employee')], default='super_admin', max_length=20),
        ),
    ]
