# Generated by Django 6.0.6 on 2026-09-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_designation_user_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
