# Generated by Django 6.0.6 on 2026-10-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order', 'order'), ('deal', 'deal'), ('happy_hour', 'happy_hour'), ('favourite', 'favourite'), ('restaurant', 'restaurant'), ('feedback', 'feedback'), ('system', 'system')], max_length=20),
        ),
    ]
