# Generated by Django 6.0.6 on 2026-06-21 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_role', models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant')], default='user', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('birthday', 'Birthday'), ('corporate', 'Corporate'), ('casual', 'Casual'), ('date_night', 'Date Night'), ('team_event', 'Team Event'), ('family', 'Family'), ('other', 'Other')], default='casual', max_length=50)),
                ('group_size', models.IntegerField(default=1)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('vibe', models.CharField(choices=[('casual', 'Casual'), ('business', 'Business'), ('fun', 'Fun'), ('romantic', 'Romantic'), ('family', 'Family')], default='casual', max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('discount_offer', models.CharField(blank=True, max_length=100)),
                ('specials', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='happy_hours/')),
                ('participants_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('upcoming', 'Upcoming'), ('draft', 'Draft'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('restaurant_response', models.TextField(blank=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='happy_hours', to='restaurants.restaurant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_happy_hours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
