# Generated by Django 6.0.6 on 2026-10-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='happyhour',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='happyhour',
            name='created_by_role',
            field=models.CharField(choices=[('user', 'User'), ('restaurant', 'Restaurant'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
