# Generated by Django 6.0.6 on 2026-10-03 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_deal_food_type'),
        ('happy_hours', '0002_happyhour_price_alter_happyhour_created_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='happyhour',
            name='price',
        ),
        migrations.AddField(
            model_name='happyhour',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_happy_hours', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='happyhour',
            name='is_deal',
            field=models.BooleanField(default=False),
        ),
    ]
